### ISSUE TITLE
Build Deployment Environment

### ISSUE THREAD

**Issue by Mjwillis** [alphagov/gdx-data-share-poc#7]

**Comment by Mjwillis** [comment]
ECS environment

**Comment by olevett** [comment]
AWS Dependencies we need to build out/set up
- Cognito for auth
- SNS for inbound/outbound services
- SQS for internal queueing
- ECS for the main application runtime
- RDS/Postgres for underlying data
- ECR for main service container

We'll additionally need to mock out/otherwise provide an implementation of
- the LEV API
- HMRCs NINO retrieval service

**Comment by Mjwillis** [comment]
We use quay at MOJ because of the virus scanning and ease of public access to use with docker-compose
